In [1]:
import __hello__

Hello world!


In [2]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [3]:
import os
os.popen(f"code {this.__file__}")

> Beautiful is better than ugly.
```
isEven=lambda Num:True if str(Num)[-1]=="2" or str(Num)[-1]=="4" or str(Num)[-1]=="8" or str(Num)[-1]=="0" or str(Num)[-1]=="6" else False 

def is_even(num):
    return num % 2 == 0
```

> Explicit is better than implicit.
```
>>> array = np.array([1,2,3])
>>> array
array([1, 2, 3])

>>> array[None]
array([[1, 2, 3]])

>>> array[np.newaxis]
array([[1, 2, 3]])
```

> Simple is better than complex.
```
>>> array = list([1,2,3,4])
>>> array
[1, 2, 3, 4]

>>> np.array(map(lambda x : x + 1, array))
array([2, 3, 4, 5])

>>> np.array(array) + 1
array([2, 3, 4, 5])
```

> Complex is better than complicated.
```
# socket
# smtplib
# googleapiclient
```

> Flat is better than nested.
```
>>> from somemodule.random.distributions.continuous import uniform
>>> from random import uniform
````

> Sparse is better than dense.
```
writer.write(cv2.line(cv2.filter2D(cv2.resize(spectrogram[:, left:left + padding * 2], shape), -1, kernel), (shape[0]//2, 0), (shape[0]//2, shape[1]), 255, 1))

image = cv2.resize(spectrogram[:, left:left + padding * 2], shape)
image = cv2.filter2D(image, -1, kernel)
image = cv2.line(image, (shape[0]//2, 0), (shape[0]//2, shape[1]), 255, 1)
writer.write(image)
```

> Readability counts.
```
>>> m = max(range(10))      
>>> n = min(range(10))
>>> m, n
(9, 0)

>>> max_value = max(range(10))      
>>> min_value = min(range(10))
>>> max_value, min_value
(9, 0)
```

> Special cases aren't special enough to break the rules.
```
object.__private = 0

object.reset()
```

> Although practicality beats purity.
```
p = prime_number(digits=20)

p = probable_prime(digits=20)
```

> Errors should never pass silently.
```
try:
    main()
except:
    pass

try:
    main()
except Exception as e:
    logging.error(f"{type(e).__name__}: {e}")
```

> Unless explicitly silenced
```
try:
    upload_progress()
except NoInternetError:
    pass
```

> In the face of ambiguity, refuse the temptation to guess.
```
> python main.py
RuntimeError: execution failed

> python main.py
Execution completed successfully

> python main.py
Execution completed successfully
```

> There should be one-- and preferably only one --obvious way to do it.
```
>>> value = 15
>>> value
15

>>> "Value is %d" % value
'Value is 15'

>>> f"Value is {value}" 
'Value is 15'
```

> Although that way may not be obvious at first unless you're Dutch.

> Now is better than never.
```
def function():
    """
    This function will ... in the most optimum manner
    """

def function()
    """
    Perform this task
    TODO: optimisation
    """
```

> Although never is often better than *right* now.
```
def function():
    """
    This function carries out this task
    """

```

> If the implementation is hard to explain, it's a bad idea.
```
# apply complex algorithm to select n Nums
y = list(f(x, n))
```

> If the implementation is easy to explain, it may be a good idea.
```
# shuffle and take first n Nums
y = random.shuffle(x)[:n]
```

> Namespaces are one honking great idea -- let's do more of those!
```
>>> definition = "x = 5\ny = 6"      
>>> print(definition)
x = 5
y = 6

>>> for assignment in definition.splitlines():    
...     exec(assignment)
...
>>> x
5
>>> y
6

>>> for assignment in definition.splitlines():    
...     variable, value = assignment.split(" = ")
...     locals()[variable] = int(value)
...
>>> x                                             
5
>>> y
6
```