In [1]:
import numpy as np

In [2]:
# arrays
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr0 = np.array(42)
arr0

array(42)

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
# dimensions
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [7]:
arr4 = np.array([1,2,3,4],ndmin=4)
arr4

array([[[[1, 2, 3, 4]]]])

In [8]:
# shape
print(arr0.shape)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)

()
(5,)
(2, 3)
(2, 2, 3)
(1, 1, 1, 4)


In [9]:
# accessing
print(arr1[2])
print(arr1[2]+arr0)
print(arr2[1][2])

3
45
6


In [10]:
print(arr2[1,2])
print(arr3[1,0,2])
print(arr4[0,0,0,-1])

6
9
4


In [11]:
# slicing
print(arr2[1,1:])
print(arr3[1,:,2])
print(arr4[0,:1,0,::-1])

[5 6]
[ 9 12]
[[4 3 2 1]]


In [12]:
# data types
print(arr0.dtype)
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)

int32
int32
int32
int32
int32


- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- S - string
- U - unicode string

In [13]:
arr1.dtype = "i2"
arr2.dtype = "b"
arr3.dtype = "f4"
arr4.dtype = "c"

In [14]:
print(arr0.dtype)
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)

int32
int16
int8
float32
|S1


In [15]:
# making changes
arr5 = np.array([1,2,3,4,5])
arr5

array([1, 2, 3, 4, 5])

In [16]:
# copy
x = arr5.copy()
x[1] = 7
print(arr5)
print(x)

[1 2 3 4 5]
[1 7 3 4 5]


In [17]:
print(arr5.base)
print(x.base)

None
None


In [18]:
# copy
x = arr5.view()
x[1] = 7
print(arr5)
print(x)

[1 7 3 4 5]
[1 7 3 4 5]


In [19]:
print(arr5.base)
print(x.base)

None
[1 7 3 4 5]


In [20]:
# reshaping
arr8 = np.array(range(8))
arr8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr8.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
arr8.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
arr8.reshape(2,2,3)

ValueError: cannot reshape array of size 8 into shape (2,2,3)

In [24]:
arr8.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
arr2.reshape(-1)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 6, 0,
       0, 0], dtype=int8)

In [26]:
# searching
np.where(arr2 > 2)

(array([0, 1, 1, 1], dtype=int64), array([8, 0, 4, 8], dtype=int64))

In [27]:
print(arr2[0,8])
print(arr2[1,8])
print(arr2[1,4])
print(arr2[1,8])

3
6
5
6


In [28]:
x = [True,False]*4
print(x)
print(arr8)
print(arr8[x])

[True, False, True, False, True, False, True, False]
[0 1 2 3 4 5 6 7]
[0 2 4 6]


In [29]:
arr8[np.where(arr8 % 3 == 0)]

array([0, 3, 6])

In [30]:
import random
listr = [random.randint(0,100) for i in range(10)]
print(*listr)

4 14 92 100 47 64 43 46 22 58


In [31]:
arrr = np.random.randint(100,size=10)
print(*arrr)

31 38 0 93 88 91 47 11 63 41


In [32]:
import time
t = time.time()
listr = [random.randint(0,100) for i in range(10**7)]
listr.sort()
listt = time.time() - t
listt

12.894912242889404

In [33]:
t = time.time()
arrr = np.random.randint(100,size=10**7)
np.sort(arrr)
arrt = time.time() - t
arrt

0.5066673755645752

In [34]:
listt / arrt

25.450449081156474